apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis-war
  name: redis-war
  namespace: miaosha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-war
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-war
    spec:
      volumes:
      - name: redis-war-cm
        configMap:
          name: redis-war-config
      containers:
      - image: 192.168.56.101:5000/redis-new
        name: redis-war
        volumeMounts:
        - name: redis-war-cm
          mountPath: /usr/local/tomcat/webapps/redis/WEB-INF/classes/application.properties
          subPath: application.properties
        ports:
        - containerPort: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-war
  name: redis-war
  namespace: miaosha
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30999
  selector:
    app: redis-war
  type: NodePort
status:
  loadBalancer: {}
